/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest_FFmpegJni */

#ifndef _Included_FFmpeg_Jni
#define _Included_FFmpeg_Jni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_apkmatrix_components_ffmpeg_jni_FFmpegJni_run(JNIEnv *, jclass, jint, jobjectArray);

JNIEXPORT void JNICALL Java_com_apkmatrix_components_ffmpeg_jni_FFmpegJni_exit(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

void ffmpeg_progress(float progress);